import fs from 'fs';
import { bounceFunctions, overshootFunctions, springFunctions, wiggleFunctions } from '~/data/easing-functions';
import { EasingType, LinearEasingAccuracy, OvershootStyleKey } from '~/types/enums';
import { generateLinearEasing } from '~/utils/easing';

function main() {
  const springCalculations = Object.fromEntries(
    Object.entries(springFunctions).map(([curve, springFunction]) => [
      curve,
      generateLinearEasing({ type: EasingType.SPRING, accuracy: LinearEasingAccuracy.HIGH, ...springFunction }),
    ]),
  );

  const bounceCalculations = Object.fromEntries(
    Object.entries(bounceFunctions).map(([curve, bounceFunction]) => [
      curve,
      generateLinearEasing({ type: EasingType.BOUNCE, accuracy: LinearEasingAccuracy.HIGH, ...bounceFunction }),
    ]),
  );

  const wiggleCalculations = Object.fromEntries(
    Object.entries(wiggleFunctions).map(([curve, wiggleFunction]) => [
      curve,
      generateLinearEasing({ type: EasingType.WIGGLE, accuracy: LinearEasingAccuracy.HIGH, ...wiggleFunction }),
    ]),
  );

  const overshootCalculations = Object.fromEntries(
    Object.entries(overshootFunctions).map(([style, curves]) => [
      style,
      Object.fromEntries(
        Object.entries(curves).map(([curve, overshootFunction]) => [
          curve,
          generateLinearEasing({
            type: EasingType.OVERSHOOT,
            accuracy: LinearEasingAccuracy.HIGH,
            ...overshootFunction,
            style: style as OvershootStyleKey,
          }),
        ]),
      ),
    ]),
  );

  // write the file ./src/generated/linear-easings.ts with the content of the calculations
  const content = `// This file is generated by scripts/generate-linear-easings.ts
import type { BounceCurveKey, OvershootCurveKey, OvershootStyleKey, SpringCurveKey, WiggleCurveKey } from '~/types/enums';
import type { Point } from '~/types/types';

type Value = {
  easingValue: string;
  sampledPoints: Point[];
};

// Do not modify it manually
export const springCalculations: Record<SpringCurveKey, Value> = ${JSON.stringify(springCalculations, null, 2)};
export const bounceCalculations: Record<BounceCurveKey, Value> = ${JSON.stringify(bounceCalculations, null, 2)};
export const wiggleCalculations: Record<WiggleCurveKey, Value> = ${JSON.stringify(wiggleCalculations, null, 2)};
export const overshootCalculations: Record<OvershootStyleKey, Record<OvershootCurveKey, Value>> = ${JSON.stringify(overshootCalculations, null, 2)};
`;

  fs.writeFileSync('./src/generated/linear-easings.ts', content);
}

main();
