import fs from 'fs';
import { bounceFunctions, overshootFunctions, springFunctions, wiggleFunctions } from '~/data/easing';
import { LinearEasingAccuracy, OvershootStyle } from '~/types-and-enums';
import {
  createBounceFunction,
  createOvershootFunction,
  createSpringFunction,
  createWiggleFunction,
  generateLinearEasing,
} from '~/utils/easing';

function main() {
  const springCalculations = Object.fromEntries(
    Object.entries(springFunctions).map(([curve, springFunction]) => [
      curve,
      generateLinearEasing(createSpringFunction(springFunction), LinearEasingAccuracy.HIGH),
    ]),
  );

  const bounceCalculations = Object.fromEntries(
    Object.entries(bounceFunctions).map(([curve, bounceFunction]) => [
      curve,
      generateLinearEasing(createBounceFunction(bounceFunction), LinearEasingAccuracy.HIGH, 1),
    ]),
  );

  const wiggleCalculations = Object.fromEntries(
    Object.entries(wiggleFunctions).map(([curve, wiggleFunction]) => [
      curve,
      generateLinearEasing(createWiggleFunction(wiggleFunction), LinearEasingAccuracy.HIGH, 1, 0),
    ]),
  );

  const overshootCalculations = Object.fromEntries(
    Object.entries(overshootFunctions).map(([style, curves]) => [
      style,
      Object.fromEntries(
        Object.entries(curves).map(([curve, overshootFunction]) => [
          curve,
          generateLinearEasing(
            createOvershootFunction({ ...overshootFunction, style: style as OvershootStyle }),
            LinearEasingAccuracy.HIGH,
            1,
          ),
        ]),
      ),
    ]),
  );

  // write the file ./app/generated/linear-easings.ts with the content of the calculations
  const content = `// This file is generated by scripts/generate-linear-easings.ts
// Do not modify it manually
export const springCalculations = ${JSON.stringify(springCalculations, null, 2)};
export const bounceCalculations = ${JSON.stringify(bounceCalculations, null, 2)};
export const wiggleCalculations = ${JSON.stringify(wiggleCalculations, null, 2)};
export const overshootCalculations = ${JSON.stringify(overshootCalculations, null, 2)};
`;

  fs.writeFileSync('./app/generated/linear-easings.ts', content);
}

main();
