import fs from 'fs';
import { bounceFunctions, springFunctions, wiggleFunctions } from '~/data/easing';
import { LinearEasingAccuracy } from '~/types-and-enums';
import { createBounceFunction, createSpringFunction, createWiggleFunction, generateLinearEasing } from '~/utils/easing';

function main() {
  const springCalculations = Object.fromEntries(
    Object.entries(springFunctions).map(([curve, springFunction]) => [
      curve,
      generateLinearEasing(createSpringFunction(springFunction), LinearEasingAccuracy.HIGH),
    ]),
  );

  console.log(springCalculations.default.sampledPoints);

  const bounceCalculations = Object.fromEntries(
    Object.entries(bounceFunctions).map(([curve, bounceFunction]) => [
      curve,
      generateLinearEasing(createBounceFunction(bounceFunction), LinearEasingAccuracy.HIGH),
    ]),
  );

  console.log(bounceCalculations.default.sampledPoints);

  const wiggleCalculations = Object.fromEntries(
    Object.entries(wiggleFunctions).map(([curve, wiggleFunction]) => [
      curve,
      generateLinearEasing(createWiggleFunction(wiggleFunction), LinearEasingAccuracy.HIGH),
    ]),
  );

  console.log(wiggleCalculations.default.sampledPoints);

  // write the file ./app/generated/linear-easings.ts with the content of the calculations
  const content = `// This file is generated by scripts/generate-linear-easings.ts
// Do not modify it manually
export const springCalculations = ${JSON.stringify(springCalculations, null, 2)};
export const bounceCalculations = ${JSON.stringify(bounceCalculations, null, 2)};
export const wiggleCalculations = ${JSON.stringify(wiggleCalculations, null, 2)};
`;

  fs.writeFileSync('./app/generated/linear-easings.ts', content);
}

main();
